export * from './About';
export * from './Contact';
export * from './FAQ';
export * from './Features';
export * from './Footer';
export * from './Header';
export * from './Hero';
export * from './Pricing';
export * from './Services';